[application]

[application.asset]
dir = "assets"

[web.app]
# HTML title tag content
title = "The Kinokov's Home Page"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

[web.application]
base_path = "https://kinoko0518.github.io/MyHomePage/"

# Javascript code file
# serve: [dev-server] only
script = []
